spring.application.name=collectorChess

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.sql.init.mode=${DB_INIT_MODE:always}
spring.sql.init.continue-on-error=${DB_INIT_CONTINUE_ON_ERROR:false}
