spring.application.name=collectorChess

spring.datasource.url=jdbc:postgresql://localhost:5432/collector_chess
spring.datasource.username=collector_chess_owner
spring.datasource.password=password
spring.sql.init.mode=always
